/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alvaroycarlos.menuimageframe;

import java.awt.Frame;
import java.io.File;
import org.opencv.core.Mat;

/**
 *
 * @author alvaroafonsolopez
 */
public class InternalFrame extends javax.swing.JInternalFrame {

    //private final Frame parentFrame;

    /**
     * Creates new form NewJInternalFrame
     */
    public InternalFrame(/*Frame parentFrame*/) {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setMaximizable(true);
        this.setIconifiable(true);
        this.setClosable(true);
        this.setFocusable(true);
        //this.parentFrame = parentFrame;
        //this.setPreferredSize(new Dimension());
    }
    
    @Override
    public void setTitle(String title){
        super.setTitle(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lienzo1 = new alvaroycarlos.menuimageframe.Lienzo();

        jMenuItem1.setText("jMenuItem1");

        lienzo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private alvaroycarlos.menuimageframe.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables

    boolean correctSize(File file) {
        return lienzo1.correctSize(file);
    }

    void loadImg(File file, boolean redimension) {
        lienzo1.loadImg(file, redimension);
    }

    void umbralizar(int res) {
        lienzo1.umbralizar(res);
    }
    
    public Mat getUmbMat(){
        return lienzo1.getUmbMat();
    }
}
